name 'sonarqube-mysql'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
license 'MIT'
description 'Installs/Configures sonarqube-mysql'
long_description 'Installs/Configures sonarqube-mysql'
version '0.1.0'
supports 'ubuntu'
supports 'centos'
depends 'database'
